### ISSUE TITLE
选择角色进入对话报错

### ISSUE THREAD

**Issue by onenov** [maioria/chatgpt-talkieai#2]
控制台日志
```
vue.runtime.esm.js:1439 Uncaught TypeError: Cannot read properties of undefined (reading 'short_name')
    at createSession (index.vue:192:47)
    at patchedFn (vue.runtime.esm.js:9747:59)
    at callWithErrorHandling (vue.runtime.esm.js:1375:22)
    at callWithAsyncErrorHandling (vue.runtime.esm.js:1384:21)
    at HTMLElement.invoker (vue.runtime.esm.js:9725:17)
createSession @ index.vue:192
patchedFn @ vue.runtime.esm.js:9747
callWithErrorHandling @ vue.runtime.esm.js:1375
callWithAsyncErrorHandling @ vue.runtime.esm.js:1384
invoker @ vue.runtime.esm.js:9725
```
后端日志：
```
INFO:     0.0.0.060020 - "OPTIONS /api/v1/languages/example?language=en-US HTTP/1.1" 200 OK
INFO:     0.0.0.060021 - "OPTIONS /api/v1/roles?locale=en-US HTTP/1.1" 200 OK
2023-10-03 14:06:50,772 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-10-03 14:06:50,772 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2023-10-03 14:06:50,772 INFO sqlalchemy.engine.Engine SELECT settings_role.id AS settings_role_id, settings_role.language AS settings_role_language, settings_role.locale AS settings_role_locale, settings_role.local_name AS settings_role_local_name, settings_role.name AS settings_role_name, settings_role.short_name AS settings_role_short_name, settings_role.country AS settings_role_country, settings_role.country_name AS settings_role_country_name, settings_role.gender AS settings_role_gender, settings_role.avatar AS settings_role_avatar, settings_role.audio AS settings_role_audio, settings_role.sequence AS settings_role_sequence, settings_role.create_time AS settings_role_create_time, settings_role.update_time AS settings_role_update_time 
FROM settings_role 
WHERE settings_role.locale = %(locale_1)s ORDER BY settings_role.name ASC
2023-10-03 14:06:50,772 - sqlalchemy.engine.Engine - INFO - SELECT settings_role.id AS settings_role_id, settings_role.language AS settings_role_language, settings_role.locale AS settings_role_locale, settings_role.local_name AS settings_role_local_name, settings_role.name AS settings_role_name, settings_role.short_name AS settings_role_short_name, settings_role.country AS settings_role_country, settings_role.country_name AS settings_role_country_name, settings_role.gender AS settings_role_gender, settings_role.avatar AS settings_role_avatar, settings_role.audio AS settings_role_audio, settings_role.sequence AS settings_role_sequence, settings_role.create_time AS settings_role_create_time, settings_role.update_time AS settings_role_update_time 
FROM settings_role 
WHERE settings_role.locale = %(locale_1)s ORDER BY settings_role.name ASC
2023-10-03 14:06:50,772 INFO sqlalchemy.engine.Engine [cached since 325s ago] {'locale_1': 'en-US'}
2023-10-03 14:06:50,772 - sqlalchemy.engine.Engine - INFO - [cached since 325s ago] {'locale_1': 'en-US'}
2023-10-03 14:06:50,774 INFO sqlalchemy.engine.Engine SELECT settings_role_style.id AS settings_role_style_id, settings_role_style.role_name AS settings_role_style_role_name, settings_role_style.style AS settings_role_style_style, settings_role_style.audio AS settings_role_style_audio, settings_role_style.example AS settings_role_style_example, settings_role_style.sequence AS settings_role_style_sequence, settings_role_style.create_time AS settings_role_style_create_time, settings_role_style.update_time AS settings_role_style_update_time 
FROM settings_role_style 
WHERE settings_role_style.role_name IN (NULL) AND (1 != 1)
2023-10-03 14:06:50,774 - sqlalchemy.engine.Engine - INFO - SELECT settings_role_style.id AS settings_role_style_id, settings_role_style.role_name AS settings_role_style_role_name, settings_role_style.style AS settings_role_style_style, settings_role_style.audio AS settings_role_style_audio, settings_role_style.example AS settings_role_style_example, settings_role_style.sequence AS settings_role_style_sequence, settings_role_style.create_time AS settings_role_style_create_time, settings_role_style.update_time AS settings_role_style_update_time 
FROM settings_role_style 
WHERE settings_role_style.role_name IN (NULL) AND (1 != 1)
2023-10-03 14:06:50,774 INFO sqlalchemy.engine.Engine [cached since 325s ago] {}
2023-10-03 14:06:50,774 - sqlalchemy.engine.Engine - INFO - [cached since 325s ago] {}
2023-10-03 14:06:50,774 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-10-03 14:06:50,774 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2023-10-03 14:06:50,775 INFO sqlalchemy.engine.Engine SELECT settings_language_example.id AS settings_language_example_id, settings_language_example.language AS settings_language_example_language, settings_language_example.example AS settings_language_example_example, settings_language_example.create_time AS settings_language_example_create_time, settings_language_example.update_time AS settings_language_example_update_time 
FROM settings_language_example 
WHERE settings_language_example.language = %(language_1)s 
 LIMIT %(param_1)s
2023-10-03 14:06:50,775 - sqlalchemy.engine.Engine - INFO - SELECT settings_language_example.id AS settings_language_example_id, settings_language_example.language AS settings_language_example_language, settings_language_example.example AS settings_language_example_example, settings_language_example.create_time AS settings_language_example_create_time, settings_language_example.update_time AS settings_language_example_update_time 
FROM settings_language_example 
WHERE settings_language_example.language = %(language_1)s 
 LIMIT %(param_1)s
2023-10-03 14:06:50,775 INFO sqlalchemy.engine.Engine [cached since 325s ago] {'language_1': 'en', 'param_1': 1}
2023-10-03 14:06:50,775 - sqlalchemy.engine.Engine - INFO - [cached since 325s ago] {'language_1': 'en', 'param_1': 1}
INFO:     0.0.0.060021 - "GET /api/v1/roles?locale=en-US HTTP/1.1" 200 OK
INFO:     0.0.0.060020 - "GET /api/v1/languages/example?language=en-US HTTP/1.1" 200 OK
2023-10-03 14:06:50,777 INFO sqlalchemy.engine.Engine ROLLBACK
2023-10-03 14:06:50,777 - sqlalchemy.engine.Engine - INFO - ROLLBACK
2023-10-03 14:06:50,777 INFO sqlalchemy.engine.Engine ROLLBACK
2023-10-03 14:06:50,777 - sqlalchemy.engine.Engine - INFO - ROLLBACK

```

步骤：创建数据库，编辑env，导入data.sql，start

**Comment by maioria** [comment]
data.sql跟数据库的表结构有问题，已经重新提交了一版
